export const ACURAST_ENVIRONMENT_VARIABLES = {
  WEBSOCKET_API_KEY: "WEBSOCKET_API_KEY",
  NODE_INFERENCE_API_KEY: "NODE_INFERENCE_API_KEY",
  NODE_TZPRO_API_KEY: "NODE_TZPRO_API_KEY",
  NODE_BAKING_BAD_BTC_API_KEY: "NODE_BAKING_BAD_BTC_API_KEY",
  NODE_BAKING_BAD_XTZ_API_KEY: "NODE_BAKING_BAD_XTZ_API_KEY",
  NODE_TEZOS_FOUNDATION_API_KEY: "NODE_TEZOS_FOUNDATION_API_KEY",
  NODE_PAPERS_API_KEY: "NODE_PAPERS_API_KEY",
};
